# Generated by Django 3.2.10 on 2024-10-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20241005_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='customerdetails',
            unique_together={('name', 'birth_date')},
        ),
        migrations.AddIndex(
            model_name='customerdetails',
            index=models.Index(fields=['name', 'birth_date'], name='api_custome_name_e30eb2_idx'),
        ),
    ]
