# Generated by Django 3.2.10 on 2024-10-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customerdetails_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
