# Generated by Django 3.2.10 on 2024-10-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customerdetails_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planet', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('significance', models.TextField()),
            ],
            options={
                'db_table': 'planet',
                'managed': False,
            },
        ),
    ]
