# Generated by Django 3.2.10 on 2024-10-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_planet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerdetails',
            unique_together=set(),
        ),
    ]
