# Generated by Django 3.2.10 on 2024-10-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customerdetails_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerdetails',
            unique_together={('mobile_no',)},
        ),
    ]
